# fly.toml app configuration file generated for naturebrawl on 2025-06-21T16:46:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'naturebrawl'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  # Health check for monitoring
  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/api/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
